import type { Metadata } from "next";
import { ClerkProvider, Show, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="flex min-h-screen gap-[2.5rem] p-[2.5rem]">
                <ClerkProvider>
                    <Sidebar />
                    <Toaster position="bottom-right" />
                    <main className="bg-colorBg2 border-borderColor2 flex-1 rounded-xl border-2 p-[2rem]">
                        {children}
                    </main>
                </ClerkProvider>
            </body>
        </html>
    );
}
